[24.11.28 / TASK-36] Feature - 로그인 페이지 제작
Check-Data-Out/velog-dashboard-v2-fe pull request #2
Opened 2024-11-28 06:43 UTC by six-standard

## 설명
![Capture-2024-11-28-153914](https://github.com/user-attachments/assets/eb7567d8-79d0-420c-8c4f-a6d6646cbe2b)
간단한 디자인을 기반으로 로그인 페이지를 제작하였습니다.

## 진행한 작업
- 페이지 퍼블리싱
- API 연동 (우선은 path만 작성해두었습니다)
- 테스트 제작 (5개의 테스트 케이스를 생성해두었습니다)

## 그 외..
Jest를 처음 사용하다 보니 조금 어색해서 오래 걸렸던 것 같습니다.
특히 jest-DOM과 mocking 작업에서 이해가 안 가는 부분이 조금 많았습니다;

2024-11-28 06:56 UTC, six-standard commented on src/app/main/page.tsx
> +import { Content } from './Content';
해당 페이지는 feature/dashboard 에서 구현할 예정입니다.
feature/init에서 파일 추가를 했어야 하는데, 실수로 해당 브랜치에서 추가된 것으로 보입니다.

2024-11-28 07:08 UTC, six-standard commented on src/app/(login)/page.tsx
> +        />
반영하였습니다!

2024-11-28 07:13 UTC, six-standard commented on src/app/main/page.tsx
> +}
반영했습니다!

2024-11-28 07:14 UTC, six-standard commented on src/utils/QueryProvider.tsx
> +const client = new QueryClient();
모든 사용자가 동일한 인스턴스를 공유하게 된다고 했는데, 정확히 무슨 의미일까요?
어디에 메모리 누수를 어떤 원리로 일으키는건지 궁금합니다. (사용자의 컴퓨터 혹은 서버)

2024-11-28 07:20 UTC, six-standard commented on src/app/(login)/page.tsx
> +  };
서버에서 직접 쿠키를 가져가는 방식으로 동작하기 때문에 위와 같이 설정하였습니다.
다만 fetch 요청 내부에서 직접 cookie 속성을 통해 전달해도 괜찮을 것 같아 해당 방식으로 변경하였습니다.

2024-11-28 07:22 UTC, six-standard commented on src/app/(login)/Content.tsx
> +  });
해당 코드는 굳이 건드리지 않아도 될 것으로 보입니다.
기본적으로 instance에서 headers를 제공해주고, message는 굳이 건드리지 않아도 될 듯 합니다.

2024-11-28 07:23 UTC, six-standard commented on src/app/(login)/Content.tsx
> +  };
해당 코드도 수정하였습니다.
cookie 전달 방식을 수정하며 같이 바뀌었습니다

2024-11-28 07:31 UTC, six-standard commented on src/utils/QueryProvider.tsx
> +const client = new QueryClient();
다만 해당 코드 자체가 'use client' 설정을 통해 client에서 쓰일 것을 염두에 두고 제작하였는데 서버에서 동작할 일이 있을지 의문입니다.

2024-11-28 07:34 UTC, six-standard commented on src/app/(login)/Content.tsx
> +        />
검증이 필요하다고 하셨는데, 따로 오류 메세지를 띄우는 방식이 존재하지 않습니다.
또한 토큰을 받아올 때 어차피 복사 - 붙여넣기 방식으로 받아오는 경우가 많을텐데 과연 토큰 형식까지 검사해야 할지 의문입니다.

로딩 상태는 isLoading과 toast를 통해 제공하는 방식으로 적용하겠습니다.

2024-11-28 07:35 UTC, six-standard commented on src/app/main/page.tsx
> +import type { Metadata } from 'next';
오히려 안 쓰이는 페이지로써 남는 문제가 생길 수 있어 해당 Import는 유지할 생각입니다.

해당 사항에 대해선 더 이상 리뷰하지 않으셔도 될 것 같습니다.

2024-11-28 07:37 UTC, six-standard commented on src/app/main/page.tsx
> +}
반영하였습니다.

2024-11-28 07:38 UTC, six-standard commented on src/utils/QueryProvider.tsx
> +const client = new QueryClient();
전역적인 QueryClient 인스턴스가 필요하여 해당 방식으로 설정하였습니다.

해당 사항에 대해서 더 이상 리뷰하지 않으셔도 될 듯 합니다.

2024-11-28 07:44 UTC, six-standard commented on src/utils/QueryProvider.tsx
> +};
말씀해주신 일부 설정값은 반영하였으나, ErrorBoundary나 Susppense 설정은 현재로썬 필요하지 않습니다.
필요할 때 적절히 추가하도록 하겠습니다.

해당 사항에 대해선 더 이상 리뷰하지 않으셔도 될 것 같습니다.

2024-11-28 07:53 UTC, six-standard commented on src/app/main/Content.tsx
> +      <p className="mt-4">구현 예정입니다</p>+{' '}
반영하였습니다!

2024-11-28 07:54 UTC, six-standard commented on src/app/main/Content.tsx
> +};
말씀해주신 임시 컴포넌트를 미리 적용해두었습니다!
처음에 dashboard 브랜치에서 구현할 거라고 말씀드렸는데, 초기 세팅 정도는 해당 브랜치에서 해도 괜찮을 것 같아 진행하였습니다.

해당 사항에 대해서는 더 이상 리뷰하지 않으셔도 될 것 같습니다.

2024-11-28 07:55 UTC, six-standard commented on src/api/index.ts
> +});
괜찮습니다.
어차피 fetch의 반환 객체 자체는 항상 일정한 만큼, 굳이 이런 방식으로 진행하지 않아도 될 것 같습니다.
또한 서버에서 커스텀 오류 메세지를 전송할 수도 있기 때문에 해당 방식을 적용하지 않았습니다.

해당 사항에 대해서는 더 이상 리뷰하지 않으셔도 될 것 같습니다.

2024-11-28 07:59 UTC, six-standard commented on src/components/Button.tsx
> +};
반영하였습니다!
다만 하드코딩된 값들은 해당 컴포넌트에서만 쓰이기 때문에 하드코딩하였다는 이유가 있습니다.
따라서, 더 이상의 수정이 필요하지 않을 것으로 보입니다.

해당 사항에 대해서는 더 이상 리뷰하지 않으셔도 될 것 같습니다.

2024-11-28 09:03 UTC, HA0N1 commented on src/__test__/login.test.tsx
refrehsInputEl  -> refreshInputEl 
테스트 코드내에 오타가 있는 거 같습니다!

2024-11-28 09:16 UTC, HA0N1 commented
FE의 테스트 코드는 처음 보는데 사용자 행동을 테스팅하는군요! 잘봤습니다

### 좋았던 점
1. describe와 it을 사용해 테스트 케이스를 그룹화하여 테스트 구조를 잘 정리 하신 거 같습니다

### 개선할 점
1. login test 파일 refrehs 오타가 난 거 같습니다
2. 에러 메시지 같은 경우에는 상수로 정의해서 사용하시면 나중에 유지보수가 쉬울 거 같습니다

2024-11-28 13:04 UTC, BDlhj requested changes
PR 잘 확인했습니다!
코멘트 남긴 모든 부분에 대해서 수정을 요청드린 건 아니니 확인하시고 기준님 판단대로 하시면 될 것 같습니다. 그러고 re-request 날려주세요~~

### 좋았던 점
1. 하온님 말씀대로 테스트를 그룹화해주셔서 이해하기 편한 것 같습니다!
2. 자주 사용되는/될 css 속성을 tailwind에서 커스텀하신 것도 앞으로 사용성 측면에서 좋다고 생각합니다👍🏻

2024-11-28 13:04 UTC, BDlhj commented on .env.simple
simple 말고 sample로 하면 어떨까 생각합니다!

2024-11-29 07:50 UTC, Nuung commented on tailwind.config.ts
> +        2: '#63E6BE',
해당 의견에 동의합니다! 기준님 외에 분들은 따라 들어가봐야만 알 수 있을 것 같아요!

2024-11-29 07:50 UTC, Nuung commented on src/components/Button.tsx
> +const formStyle = {
요런 철저한 상수값은 전체 대문자로 하는것은 어떨까요?

2024-11-29 07:53 UTC, Nuung commented on src/api/index.ts
> +  throw new Error('BASE_URL가 ENV에서 설정되지 않았습니다.');
당연히 기준님도 계획하고 계시겠지만

에러 헨들링은 따로 디렉토리를 파고
Error 객체를 상속받는 CustomError 들을 만들고, 해당 에러들은 각자의 "code" 값을 가지며
무엇보다 "누구나" 한 번에 "디버깅하기 쉬운" 형태가 되어야 할 것 같아요!

PS) 
https://accreditly.io/articles/a-comprehensive-guide-to-exception-handling-in-javascript#content-creating-custom-error-types

2024-11-29 07:55 UTC, Nuung requested changes
### 좋았던 사항
- ㅋㅋㅋㅋ벌써 많은 전쟁을 치룬 뒤에 보게 된 것 같아, 훨씬 뭐랄까 피땀눈물이 느껴진달까..? 고생많으셨어요
- FE 에서 테스트 쉽지않은데 정말로, 깔끔한 성공 / 실패 테스트케이스 인 것 같아요. 특히 랜더링 체크에서요 :) 
- 이제 셀레니움등을 활용한 테스트도 (지금 전혀 필요없음) 살짝씩 체크해보시면 어떨까? 라는 생각도 듭니다 :) 

### 개선 사항
1. 개별 코멘트 한 번 확인해 주세요!
2. 테스트 코드에서 "서버가 문제가 있을때" 에 대한 케이스가 없는 것 같습니다!

2024-11-29 08:35 UTC, six-standard commented on .env.simple
> +NEXT_PUBLIC_BASE_URL=<server's url here>
현재 Husky 적용이 안 되어있는데, 적용하는 과정에서 추가하면 될 듯 합니다.

다만 왜 new line이 필요한지 궁금한데, 혹시 간단하게라도 설명해주실 수 있을까요?

2024-11-29 08:40 UTC, Nuung commented on .env.simple
> +NEXT_PUBLIC_BASE_URL=<server's url here>
원초적으로는 OS 간 호환성 때문에 그래요! 라인피드, 캐리지리턴 때문이고, 사실 심플하게는 이로 인해 생긴 POSIX 명세 규칙이 현대까지 규칙처럼 잡혀 있어서 그렇습니다~

2024-11-29 09:03 UTC, six-standard commented on tailwind.config.ts
> +        2: '#63E6BE',
해당 의견은 저도 고민해봤던 부분인데, 네이밍을 어떻게 정해야 적절하다는 평을 들을지 모르겠더군요.
그래서 우선은 Velog가 정해둔 방식에 따라 맞춰둔 것이긴 합니다.

혹시 좋은 의견 있으실까요?

2024-11-29 09:07 UTC, six-standard commented on .env.simple
이름 작성 도중에 오타가 났던 것 같습니다.
해당 이슈 반영하였습니다!

2024-11-29 09:10 UTC, six-standard commented on src/components/Button.tsx
> +const formStyle = {
typescript에서 해당 속성의 타입을 인식하는데 문제가 있어 임시로 정해두었습니다.
원래 저 속성이 저 형태의 상수값을 제공하는데, 타입 지정을 하지 않고 사용하려 하니 문제가 생기더군요 

사실 입력 컴포넌트에서도 type 속성만 인식을 못 하는 이상한 문제가 있는데, 리팩토링 브랜치를 만들어서 추후에 해결해볼 계획입니다.
당장 급한 요소는 아니거든요 (어차피 input 타입이라 해봤자 date, password, text 셋 중 하나라서요)

2024-11-29 09:11 UTC, Nuung commented on src/components/Button.tsx
> +const formStyle = {
넵!

2024-11-29 09:12 UTC, Nuung commented on tailwind.config.ts
> +        2: '#63E6BE',
light / medium / dark 이런건 어떨까요?!

2024-11-29 09:12 UTC, six-standard commented on .env.simple
> +NEXT_PUBLIC_BASE_URL=<server's url here>
해당 부분 잘 이해했습니다!

생각해보니 원래 Prettier가 자동으로 New line 처리를 해줬던 걸로 기억하는데, 규칙 정의가 안 되어있는 듯 합니다.
해당 사항 반영해서 커밋하겠습니다.

2024-11-29 10:01 UTC, six-standard commented on src/__test__/login.test.tsx
> +    );
반영했습니다!

2024-11-29 10:01 UTC, six-standard commented on .env.simple
> +NEXT_PUBLIC_BASE_URL=<server's url here>
반영하였습니다!

2024-11-29 10:03 UTC, six-standard commented on src/__test__/login.test.tsx
오타 수정 완료했습니다!

2024-11-29 10:05 UTC, six-standard commented on tailwind.config.ts
> +        2: '#63E6BE',
괜찮을 것 같습니다.
현재 light / medium / dark, dark / medium / light가 혼용되고 있는데 이해하기도 훨씬 쉬울 것 같네요!

반영하고 리졸브하겠습니다

2024-11-29 10:11 UTC, six-standard commented on tailwind.config.ts
> +        2: '#63E6BE',
반영해봤는데, 조금 아쉬울 것 같습니다.

배경 색(BG)는 검은색이 메인, 짙은 회색이 서브, 회색이 다른 서브입니다.
그런데 텍스트 색(TEXT)는 하얀색이 메인, 옅은 회색이 서브, 회색이 다른 서브입니다.

따라서 오히려 light/dark 네이밍으로 인해 혼란을 일으키지 않을까 싶습니다.

2024-11-29 10:18 UTC, six-standard commented on src/api/index.ts
> +  throw new Error('BASE_URL가 ENV에서 설정되지 않았습니다.');
아직 에러 핸들링에 관해서 생각을 못 해봤는데, 확인해보니 그 부분이 부족한 것 같습니다.
특히 참여했던 프로젝트들에서 Custom Error를 따로 생성하여 핸들링한 경험이 부족합니다.
그래서 그냥 HTTP 응답 코드에 맞춰 토스트를 띄울까 생각했는데, 제공해주신 레퍼런스 보고 에러 핸들링을 좀 공부해서 적용해보겠습니다.

우선은 추가 브랜치 (refactor/handling 등..)을 통해 개선하는 방식이 좋을 것 같은데, 어떻게 생각하시나요? @Nuung

2024-11-29 11:43 UTC, Nuung commented on src/api/index.ts
> +  throw new Error('BASE_URL가 ENV에서 설정되지 않았습니다.');
@six-standard 넵! 이번 PR 에 끝내기엔 확실히 해비한게 맞습니다!
기본적인 디렉토리 세팅이나 전체 골자는 한 번 잡아보는 것도 좋습니다!

2024-11-29 11:44 UTC, Nuung commented on tailwind.config.ts
> +        2: '#63E6BE',
그럼 차라리 main / sub / 등의 수단적 분할은 어떨까요?

2024-11-29 12:28 UTC, BDlhj commented on tailwind.config.ts
> +        2: '#63E6BE',
이 부분이 굉장히 어렵군요... 아니면 'black-light'나 'black-main'과 같이 '색상'과 '명도' 또는 '색상'과'수단' 조합은 별로일까요??🤔

2024-11-29 13:00 UTC, HA0N1 commented on tailwind.config.ts
> +        2: '#63E6BE',
뭘 기준으로 나누게 파악했는지가 중요할 거 같습니다
사용빈도 순으로 한다면 현우님 말씀대로 main / sub / alt 같은 방식이 좋을 거 같고
색을 기준으로 잡는다면 main / subDark / subLight 같은 형식이 좋을 거 같습니다!

사용 할때를 고려한다면 bg-main bg-subDark 식으로 나오는게 조금 더 나을 거 같습니다!

2024-11-29 13:47 UTC, six-standard commented on src/api/index.ts
> +  throw new Error('BASE_URL가 ENV에서 설정되지 않았습니다.');
알겠습니다.
그럼 이 사항은 다른 브랜치로 넘기도록 하겠습니다!

2024-11-29 13:48 UTC, six-standard commented on tsconfig.json
> +  ],
ESLint 세팅 파일에서 오류가 발생하여 적용한 코드입니다.
제거하지 않는 게 좋을 것으로 보입니다.

2024-11-29 13:53 UTC, six-standard commented on tailwind.config.ts
> +        2: '#63E6BE',
그럼 우선은 main / sub / alt 로 적용하겠습니다.

현 상황에서 그나마 맞는 방식으로 보이네요.

2024-11-29 13:59 UTC, six-standard commented on tailwind.config.ts
> +        2: '#63E6BE',
반영했습니다!

2024-11-29 14:03 UTC, HA0N1 approved these changes

2024-11-29 14:54 UTC, BDlhj approved these changes
힘든 싸움을 하셨군요..!! 수고하셨습니다👏🏻

2024-11-29 16:37 UTC, six-standard commented
> ### 좋았던 사항
> * ㅋㅋㅋㅋ벌써 많은 전쟁을 치룬 뒤에 보게 된 것 같아, 훨씬 뭐랄까 피땀눈물이 느껴진달까..? 고생많으셨어요
> * FE 에서 테스트 쉽지않은데 정말로, 깔끔한 성공 / 실패 테스트케이스 인 것 같아요. 특히 랜더링 체크에서요 :)
> * 이제 셀레니움등을 활용한 테스트도 (지금 전혀 필요없음) 살짝씩 체크해보시면 어떨까? 라는 생각도 듭니다 :)
> 
> ### 개선 사항
> 1. 개별 코멘트 한 번 확인해 주세요!
> 2. 테스트 코드에서 "서버가 문제가 있을때" 에 대한 케이스가 없는 것 같습니다!

"서버에 문제가 있을때" 케이스에 대해서는 리팩토링 브랜치에서 진행하도록 하겠습니다.
해당 부분이 커스텀 에러 핸들링과 겹칠 것으로 보이는데, 커스텀 에러 핸들링을 리팩토링 브랜치에서 작업할 예정이어서요.

2024-11-30 04:27 UTC, Nuung approved these changes
고생 너무많으셨어요! 리펙토링 브랜치를 기약합시다! 아자아자!

2024-11-30 04:29 UTC, merged