[24.12.06 / TASK-48] Refactor - 커스텀 에러 핸들링 추가
Check-Data-Out/velog-dashboard-v2-fe pull request #3
Opened 2024-12-06 05:04 UTC by six-standard

커스텀 에러 추가와 기타 리팩토링 요소들을 리팩토링하였습니다!

2024-12-06 05:09 UTC, six-standard commented
브랜치 정리 과정에서 뭔가 꼬인건지 다른 브랜치들의 커밋이 여기 쌓였네요;
오래된 커밋들은 무시하고 리뷰해주시면 될 것 같습니다!

2024-12-07 01:03 UTC, Nuung commented on src/__test__/login.test.tsx
> +import { Login } from '@/app';
(import 순서, 아래 slack 으로..)
https://velogdashboard.slack.com/archives/C08062PN5PV/p1733494995798009

2024-12-07 01:49 UTC, Nuung commented on src/api/index.ts
> +const ABORT_MS = 1000 * 5;
이건 배포되는 환경마다 다를 수 밖에 없을 것이라, 환경 변수로 빼도 될 것 같아요. 아마 운영 환경에서는 30초가 되지 않을까 합니다!

2024-12-07 01:54 UTC, Nuung commented on src/errors/fetchErrors.ts
this.name 은 class name 으로 js level 에서 자동으로 넣어주는 것으로 알고 있습니다!
this.name 을 다 따로 명시한 이유가 있을까요~?!
`this.code` 등을 정해서 error docs 를 따로 만드는게 더 맞는 것 같아요!

2024-12-07 01:56 UTC, Nuung commented on src/api/index.ts
> +        throw new Error(`알 수 없는 오류가 발생했습니다 ${err.name}`);
혹시 이 메시지를 띄우실 예정이라면, "알 수 없는 오류" 와 같은 메시지는 유의미하지 않을 것 같아요!
차라리 서버쪽 에러라고 정확하게 표시하는게 좋을 것 같습니다! 

PS. 띄우지 않아도 저는 개인적으로 "알 수 없는 오류" 단어 자체를 별로 선호하지 않아서, 서버 쪽 에러 명시가 어떨까요?!

2024-12-07 02:01 UTC, Nuung commented on src/components/QueryProvider.tsx
> +}
부모 컴포넌트가 넘기는 prop , children 을 위한 타입이라고 이해하고 좋은 것 같으나 

1. 다른 곳에서 omit , extends DetailedHTMLProps 등을 활용해서 오히려 이 인터페이스 활용도가 더 낮은 것 같아요. 
2. ReactNode 는 이미 ReactElement 를 포함하고 있는데, 이 형태의 children 은 명시하는 목적이 불분명한 것 같아요.

2024-12-07 02:01 UTC, Nuung commented on src/components/Input.tsx
>  const formStyle = {
이런 컴포넌트, 페이지에 귀속되는 "상수" 는 대문자 처리 하셨던 syntax 에 맞추는게 좋을 것 같아요!

2024-12-07 02:05 UTC, Nuung commented on src/api/index.ts
> +  setTimeout(() => controller.abort(new DOMException('TimeoutError')), ms);
옙,, 코드 레빗 말이 맞는 것 같네요 `setTimeout(() => controller.abort(), timeout);`

2024-12-07 02:09 UTC, Nuung requested changes
### 좋았던 점

1. 깔끔한 커스텀 에러 처리와 fetch instance 처리 아주 좋았어요, 특히 abortPolyfill 로 지원하지 않는 run-time 에서도 대응하신 점!
2. 타입 사용과 선언에 고민이 느껴집니다,, 빡세네요. ? 와 같은 `Optional Chaining` 도 놓치지 않네요!

### 아쉬운 점
1. import 는 slack 으로 대체 할게요!
2. 그 외 댓글 한 번 참조해주세요 :)

2024-12-07 02:50 UTC, six-standard commented on src/errors/fetchErrors.ts
this.name이 자동으로 들어갈 거라는 생각을 못 했습니다..

그런데 혹시 error docs를 따로 만들어야 할 이유가 무엇일까요?
개인적으로 name을 통해 직관적으로 보는게 docs에서 에러 코드를 찾아서 보는것보다 나을 것 같다고 생각하다 보니, 이해하기가 조금 어렵습니다.

2024-12-07 02:51 UTC, six-standard commented on src/api/index.ts
> +  setTimeout(() => controller.abort(new DOMException('TimeoutError')), ms);
반영했습니다.
this.name 이슈와 같은 이유로 이렇게 처리하였습니다;;

2024-12-07 05:29 UTC, six-standard commented on src/api/index.ts
> +const ABORT_MS = 1000 * 5;
반영했습니다!

2024-12-07 06:34 UTC, BDlhj approved these changes
잘 봤습니다!
간단하게 코멘트 남겨놓았습니다!!

### 좋았던 점
- 커스텀 에러 타입을 만드신 부분과 디렉토리 구조가 잘 잡힌 부분이 좋았습니다👍🏻

2024-12-07 06:34 UTC, BDlhj commented on src/api/index.ts
> +if (!BASE_URL || isNaN(ABORT_MS)) {
위에서 ABORT_MS는 검사하는 것 같은데 왜 여기에서 한 번 더 검사하는 건가요?

2024-12-07 14:12 UTC, Nuung commented on src/errors/fetchErrors.ts
https://learn.microsoft.com/ko-kr/rest/api/storageservices/common-rest-api-error-codes

일련의 예시로, 실제 많은 S/W 가 위와 같은 docs 를 만들어 둡니다~ 
code 값을 기반으로 정형화해서 docs 로 하나 장표 정도로 정리해두고, 실제 많은 회사에서 하는 방법이죠!

2024-12-08 08:14 UTC, six-standard commented on src/api/index.ts
> +        throw new Error(`알 수 없는 오류가 발생했습니다 ${err.name}`);
반영했습니다!

2024-12-08 08:15 UTC, six-standard commented on src/components/QueryProvider.tsx
> +}
반영했습니다!

2024-12-08 08:19 UTC, six-standard commented on src/errors/fetchErrors.ts
알겠습니다!
해당 부분 반영하겠습니다~

2024-12-08 13:30 UTC, six-standard commented on src/api/index.ts
> +if (!BASE_URL || isNaN(ABORT_MS)) {
엇 아닙니다;
이전에 작성해두고 제거하지 않은 것 같네요
제거 후 반영했습니다~

2024-12-08 13:31 UTC, six-standard commented on src/api/index.ts
>  });
파싱 처리는 instance 함수에서 자동으로 반영합니다.
content-type는 추가해두겠습니다!

2024-12-08 15:21 UTC, six-standard commented on src/components/Input.tsx
>  const formStyle = {
반영했습니다!

2024-12-09 09:21 UTC, Nuung approved these changes

2024-12-09 09:53 UTC, HA0N1 commented
잘봤습니다!

### 좋았던 점
- 커스텀 에러 처리와 테스트들이 모듈화 되어 관리도 보기에도 좋은 것 같습니다

### 그 외
- API 에러 처리시 status code별 에러 매핑을 객체로 분리하면 관리가 더 용이할 것 같습니다!

2024-12-09 09:53 UTC, HA0N1 approved these changes
잘봤습니다!

좋았던 점
커스텀 에러 처리와 테스트들이 모듈화 되어 관리도 보기에도 좋은 것 같습니다
그 외
API 에러 처리시 status code별 에러 매핑을 객체로 분리하면 관리가 더 용이할 것 같습니다!

2024-12-09 15:44 UTC, merged